cloudwego/kitex-tests

generic/map/client_test.go
generic/map/handler.go
idl/tenant.thrift
thriftrpc/normalcall/normalcall_test.go
thriftrpc/server.go

Feat: Add oneway test cases to check whether the server can receive requests.

feat: add oneway server check

---

grpc/unknown_handler/unknown_service_handler_test.go
idl/unknown_handler.proto
run.sh

en: add grpc unknown service handler test
zh: 为 grpc unknown service handler 场景添加单测

chore: add grpc unknown service handler test

---

.github/workflows/codeql-analysis.yml
.github/workflows/push-check.yml
idl/base.thrift
thriftrpc/client.go
thriftrpc/retrycall/retrycall_mockresult.go
thriftrpc/retrycall/retrycall_test.go

feat
en:  feat: add test for specified result retry
zh: feat: 增加指定结果重试测试
none

feat: add test for specified result retry

---

run.sh

fix
en: remove mvdan.cc/gofumpt to keep compatibility with lower version of go
zh: 移除 mvdan.cc/gofumpt 以保持对低版本 go 的兼容

compatibility

---

pbrpc/failedcall/error_handler/errhandler_test.go
pbrpc/failedcall/error_handler/mockfailed_handler.go
thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/error_handler/mockfailed_handler.go

feat
en: add test cases for feat `biz error`
zh: 为biz error功能添加测试用例
https://github.com/cloudwego/kitex/pull/613

feat: add test cases for feat biz error

---

pbrpc/failedcall/error_handler/mockfailed_handler.go

fix 
en: fix: fix test case for gRPC biz error
zh: fix: 修复gRPC biz error的测试用例

fix: biz error tests

---

.github/workflows/push-check.yml
run.sh

fix
en: overall coverage statistics invalid after adding integration test coverage statistics
zh: 修复增加集成测试覆盖率统计后整体覆盖率统计失效问题

fix: overall coverage statistics invalid after adding integration test coverage statistics

---

thriftrpc/muxcall/thriftmux_test.go

fix
en: fix: make client not gced
zh: fix: 让 client 不要被 gc

fix: make client not gced

---

pbrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/failedcall_test.go
thriftrpc/failedmux/error_handler/errhandler_test.go
thriftrpc/failedmux/failedmux_test.go
thriftrpc/normalcall/normalcall_test.go
thriftrpc/retrycall/retrycall_test.go

chore
en: chore: use global cli var
zh: chore: use global cli var

chore: use global cli var

---

thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/error_handler/mockfailed_handler.go

feat
en: feat: add test cases with fallback feature

feat: add test cases with fallback feature

---

thriftrpc/retrycall/retrycall_test.go

feat
en: feat: add failure retry test
zh: feat: 重试失败重试的测试

feat: add failure retry test

---

.gitignore
grpc/compressor/grpc_client.go
grpc/compressor/grpc_compressor_test.go
grpc/compressor/grpc_server.go
grpc/compressor/kitex_client.go
grpc/compressor/kitex_server.go
idl/grpc_demo.proto
idl/grpc_demo_2.proto
run.sh

test
test: 为 grpc 压缩场景添加测试
en:
zh(optional):

test: add grpc test for grpc compressor

---

grpc/compressor/grpc_compressor_test.go
run.sh

This reverts commit 8d49b6e8ed137a183163615845c4c281e187c5a1.
en:
zh(optional):

Revert "test: grpc fix shell (#28)"

---

thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedmux/error_handler/errhandler_test.go

chore: update test case for handler panic info modification

---

.gitignore
grpc/compressor/grpc_client.go
grpc/compressor/grpc_compressor_test.go
grpc/compressor/grpc_server.go
grpc/compressor/kitex_client.go
grpc/compressor/kitex_server.go
idl/grpc_demo.proto
idl/grpc_demo_2.proto
run.sh

Reverts cloudwego/kitex-tests#30

Revert "Revert "test: add grpc test for grpc compressor""

---

grpc/compressor/grpc_compressor_test.go
run.sh

Reverts cloudwego/kitex-tests#29

Revert "Revert "test: grpc fix shell (#28)""

---

thriftrpc/retrycall/percentage_limit_test.go
thriftrpc/retrycall/retrycall_mockresult.go

test: Adding missing tests or correcting existing tests
en: test the new feature of limiting the percentage of retry requests, and also test it after policy update
zh(optional): 
https://github.com/cloudwego/kitex/pull/1117

test: percentage limit, with policy update

---

codegen/.gitignore
codegen/basic_idls/kitex/base.thrift
codegen/basic_idls/kitex/example.thrift
codegen/basic_idls/thrift/loop/packb/common.thrift
codegen/basic_idls/thrift/loop/packb/packa/common.thrift
codegen/basic_idls/thrift/test.thrift
codegen/basic_idls/thrift/test_compatible_names.thrift
codegen/basic_idls/thrift/test_ignore_initialisms.thrift
codegen/basic_idls/thrift/test_method_ret.thrift
codegen/basic_idls/thrift/test_typedef_name_conflict.thrift
codegen/codegen_install_check.sh
codegen/codegen_run.sh

test
test: 为 codegen 增加测试
en:
zh(optional):

test: add codegen test

---

codegen/basic_idls/kitex/example.thrift

test
test: 给 codegen 增加 testcase
en:
zh(optional):

test:  add testcase for codegen

---

grpc/multi_service/multi_service_test.go
grpc/unknown_handler/unknown_service_handler_test.go
idl/multi_service.proto
idl/multi_service_2.proto
run.sh

test: add test for gRPC multi-service

---

thriftrpc/retrycall/retrycall_test.go

test
en: add the case fixed in https://github.com/cloudwego/kitex/pull/1194
zh(optional):

test: add test case for retry RespOp isolation

---

pbrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedmux/error_handler/errhandler_test.go

ci
en: handler panic message contains `servicename.method` instead of `method`
zh(optional):

fix: panic error contains servicename

---

grpc/normalcall/normalcall_test.go
thriftrpc/muxcall/thriftmux_test.go
thriftrpc/normalcall/normalcall_test.go

test
en: add client/server test for disabling rpcinfo reuse
zh(optional):

test: disable rpcinfo reuse

---

run.sh
thrift_streaming/generate.sh
thrift_streaming/kitex_gen/echo/echoservice/echoservice.go
thrift_streaming/kitex_gen/grpc_pb/pbservice/pbservice.go
thrift_streaming/kitex_gen/kitex_pb/pbservice/pbservice.go
thrift_streaming/kitex_gen_slim/echo/echoservice/echoservice.go

fix
en: previous impl fails to run in this repo (only considered running on cloudwego/kitex)
zh(optional):

fix: run thrift-streaming codegen without LOCAL_REPO

---

thrift_streaming/thrift_tracing_test.go

fix: support biz status error for streaming

---

thriftrpc/normalcall/normalcall_test.go

test
zh: test: 添加 crc32校验的测试
en:
zh(optional):

test: add crc32 check test

---

generic/json/client_test.go
generic/json/handler.go
generic/json/server.go

feat: add generic call test cases

---

thriftrpc/normalcall/normalcall_test.go

Reverts cloudwego/kitex-tests#61

Revert "test: add crc32 check test"

---

thrift_streaming/thrift_tracing_test.go

test: client recv io.EOF is not an error; codegen client stream should impl WithDoFinish

---

thrift_streaming/thrift_test.go

test: customMetaHandler

---

thriftrpc/normalcall/normalcall_test.go

test: custom circuit breaker error type func

---

kitexgrpc/normalcall/normalcall_test.go

test: gRPC short connection should be closed after call

---

codegen/basic_idls/kitex/example.thrift

test: thrift streaming codegen for thriftgo ci

---

.github/workflows/push-check.yml
run.sh

chore: go get latest grpc dependency to solve the compile problem of official grpc

---

idl/instparam.thrift
idl/stability.thrift
run.sh
thriftrpc/abctest/abc_test.go
thriftrpc/client.go
thriftrpc/normalcall/normalcall_test.go
thriftrpc/server.go

feat: add thrift default value check

---

thriftrpc/normalcall/normalcall_test.go

fix
调整 SkipDecoder 相关测试
en:
zh(optional):

fix: adjust SkipDecoder tests

---

run.sh
thrift_streaming/generate.sh
thrift_streaming/main_test.go

chore: output version of kitex

---

generic/http/client_test.go
generic/http/server.go
generic/json/client_test.go
generic/json/server.go
generic/map/client_test.go
generic/map/server.go
pbrpc/failedcall/error_handler/errhandler_test.go
pbrpc/muxcall/muxcall_test.go
pbrpc/normalcall/normalcall_test.go

optimize/fix
en:
zh(optional):

optimize: fix the address format and sleep duration

---

run.sh
thrift_streaming/generate.sh
thriftrpc/abctest/abc_test.go
thriftrpc/failedcall/error_handler/errhandler_test.go
thriftrpc/failedcall/failedcall_test.go
thriftrpc/failedmux/error_handler/errhandler_test.go
thriftrpc/failedmux/failedmux_test.go
thriftrpc/muxcall/thriftmux_test.go
thriftrpc/retrycall/retrycall_test.go

fix: sonic compatibility with Go and listen issues

---

codegen/codegen_run.sh

fix
fix: 删除 codegen test 里的 go.mod 依赖检查
en:
zh(optional):

fix: remove dependency check in codegen test

---

idl/grpc_multi_service.proto
idl/grpc_multi_service_2.proto
idl/thrift_multi_service_2.thrift
kitexgrpc/multi_service/multi_service_test.go
run.sh
thriftrpc/multiservicecall/multi_service_test.go

test: add tests for unknown service/method exception

---

thriftrpc/normalcall/normalcall_test.go

test: payload validator

---

thriftrpc/retrycall/mixedretry_test.go

test: add test cases for mixed retry

---

thrift_streaming/thrift_tracing_test.go

fix: resolve TracerNormalEndOfStream issue

---

thriftrpc/normalcall/normalcall_test.go

test: add test cases BenchmarkThriftWithComplexData

---

.github/workflows/pr-check.yml
kitexgrpc/compressor/grpc_compressor_test.go
kitexgrpc/compressor/kitex_client.go
kitexgrpc/multi_service/multi_service_test.go
kitexgrpc/normalcall/normalcall_test.go
kitexgrpc/unknown_handler/unknown_service_handler_test.go
pkg/utils/client.go
pkg/utils/client_test.go
thrift_streaming/generate.sh

fix(kitexgrpc): test time >1m -> 2s

---

run.sh

chore: timing run.sh

---

generic/json/client_test.go
generic/json/server.go
run.sh

test(generic): add test for generic with CombineServices parse mode

---

run.sh

en: revert temporary version change introduced by https://github.com/cloudwego/kitex-tests/pull/97
zh(optional):

chore: revert temporary version changes in run.sh

---

thrift_streaming/thrift_tracing_test.go

fix: stream recv stat should equal to send stat

---

run.sh
thrift_streaming/generate.sh

fix: work with latest kitex

---

thriftrpc/retrycall/policychange_test.go

test(retry): add test cases to check invalid retry policy

---

thrift_streaming/thrift_test.go

fix: streaming call received empty trailers

---

thriftrpc/crrst/crrst_test.go
thriftrpc/server.go

feat: test setting crrst flag

---

run.sh
thrift_streaming/generate.sh

* cache github.com/cloudwego/kitex develop version
* test modules with tests
* use replace instead of go get for some deps
optimize
en:
zh(optional):

optimize: faster run.sh

---

.github/workflows/pr-check.yml
pbrpc/failedcall/error_handler/errhandler_test.go
pbrpc/failedcall/error_handler/mockfailed_handler.go

fix
en:
WithDetails only  works with the official protobuf codec, and we'd like introduce our impl `cloudwego/prutal`
zh(optional):

fix: grpc WithDetails if not proto.Message

---

run.sh
streamx/idl/echo.thrift

see: #105
fix
en:
zh(optional):

fix: issues introduced by #105

---

thriftrpc/normalcall/normalcall_test.go

test: rm unused Basic & SkipDecoder codec tests

---

generic/http/handler.go
pkg/utils/utils.go
thriftrpc/client.go
thriftrpc/failedmux/failedmux_test.go
thriftrpc/utiltest/util_test.go

optimize
optimize: 移除代码里的 apache 依赖库用法
en:
zh(optional):

optimize: remove apache dependency

---

streamx/proto/proto_test.go
streamx/thrift/thrift_test.go

feat: adjust streaming protocol priority

---

generic/grpcbinarypb/generic_init.go
generic/grpcbinarypb/generic_test.go
generic/grpcbinarypb/idl/pbapi.proto
idl/pbapi.proto
run.sh

Change-Id: I3497517754744f438835854859873efa31c46640
test
en:
zh(optional):

test: add grpcbinarypb test

---

generic/streamxbinarypb/generic_init.go
generic/streamxbinarypb/generic_test.go

test: add streamxbinarypb test

---

streamx/thrift/thrift_test.go

feat: stream biz error

---

streamx/thrift/thrift_test.go
streamx/thrift/ttstream.go

feat: add ttstream handler options

---

thrift_streaming/thrift_tracing_test.go

test: add TestStream_DoFinishOnError test case
en:
zh(optional):

test(streaming): add reporting err when creating stream failed test

---

generic/grpcbinarypb/generic_test.go
generic/streamxbinarypb/generic_init.go
generic/streamxbinarypb/generic_test.go

Change-Id: I0e7bf03b7c32474a858ab1f739dbd8601e2b3380
test
en:
zh(optional):

test: update bianrypb test

---

generic/streamxjson/generic_init.go
generic/streamxjson/generic_test.go
generic/streamxjson/idl/echo.thrift
generic/streamxmap/generic_init.go
generic/streamxmap/generic_test.go
generic/streamxmap/idl/echo.thrift

Change-Id: I7d4d13098dadba890ba37621030f2485104ea732
test
en:
zh(optional):

test: add generic ttstream test

---

streamx/thrift/ttstream.go

refactor: update ttstream MetaFrameHandler function signature

---

run.sh

fix: go 1.18 script var

---

generic/binarypb/generic_test.go
generic/binarythrift/generic_test.go
generic/unknown_handler/generic_test.go
idl/tenant.thrift
streamx/thrift/cancel_test.go
streamx/thrift/common_test.go
streamx/thrift/thrift_test.go

test: support ttstream cancel

---

streamx/proto/proto_test.go
streamx/thrift/thrift_test.go
streamx/utils.go

test
test(gRPC): gRPC ClientStreaming 模式接收远端 handler 返回的 err
en:
zh(optional):

test(gRPC): gRPC ClientStreaming recv err returned by remote handler

---

generic/proxy/proxy.go
generic/proxy/proxy_test.go

feat: streaming proxy tests

---

run.sh

feat: update go version to 1.19

---

run.sh

Reverts cloudwego/kitex-tests#139

Revert "feat: update go version to 1.19"
